### ISSUE TITLE
Start Time only goes back upto an year.

### ISSUE THREAD

**Issue by ee07dazn** [ankurnuk365/airflow-backfill-util#1]
Start Time only goes back upto an year.

Hi Ankur 

I am trying to use this but when i try to set the Start Date back to 2016 for example: it only goes back upto an year. 

Any reason why?

Before July 2018, eveything is grey'd out

Also, the print statements in backfill code throw error with python 3.6 but that's not an important issue

**Comment by ankurnuk365** [comment]
Hi,

Apologies for replying late.

I think its more of limitation with airflow backfill cli. Don't know any other specific reason for why its happening.

**Comment by ankurnuk365** [comment]
> Hi,
> 
> Apologies for replying late.
> 
> I think its more of limitation with airflow backfill cli. Don't know any other specific reason for why its happening.

Sorry for wrong information - thats not Airflow CLI limitation. It was set in code that it should not be greater than a year. In recent commit - this has been fixed.

Thanks

**Comment by ee07dazn** [comment]
Thanks!!
