### ISSUE TITLE
why not nohup instead of screen because you never come back to the screen?

### ISSUE THREAD

**Issue by shopee-jin** [ankurnuk365/airflow-backfill-util#10]

**Comment by AnkurChoraywal** [comment]
Hi @shopee-jin, Nice Idea. As its a CLI command - we just need to run it somewhere as background task from where we can see logs anytime by attaching back the screen (if you've access to VM/Airflow Environment), where nohup is also a good choice and its just about the preference and flexibility. 
If you've code ready with "nohup", let's create a pull request.
