### ISSUE TITLE
Only visible to Admin - Maybe best to move to Browse section

### ISSUE THREAD

**Issue by ee07dazn** [ankurnuk365/airflow-backfill-util#9]
Hi @AnkurChoraywal : first of all, thanks for building the plugin. 

One thing i noticed is that when we rbac and anyone instead of Admin logs into Airflow they are not able to see it even though the admin has given the user permissions. For this reason, I made some changes on your plugin, whereby i moved it from Admin to Browse section. Now, when i provide permissions to other users, who are not admin, they can see and use the plugin. 

Just a suggestion to see what you think about this change ? And would it make sense to do on yours ?

**Comment by AnkurChoraywal** [comment]
Hi @ee07dazn that seems like a good plan. Please raise a pull request for the same if you've the code ready.
